// scale map

const map = document.querySelector('.world__map');
const zoomInBtn = document.querySelector('.zoomIn');
const zoomOutBtn = document.querySelector('.zoomOut');
const container = document.querySelector('.container');


let scale = 1;
let maxScale = 1.5;
let minScale = 0.8;
let containerWidth = container.offsetWidth;

function transformMap(btn) {
    if (!btn) {
        return;
    } else {
    btn.addEventListener('click', function () {

        if (btn === zoomInBtn && scale < maxScale) {
            scale += 0.1;
        }

        if (btn === zoomOutBtn && scale > minScale) {
            scale -= 0.1;
        }
        map.style.transform = `scale(${scale})`;
        updateMarkerPositions(containerWidth, scale);
    });
    }
}

function updateMarkerPositions (containerWidth, scale) {

    let eagleMarker = document.querySelector('.eagles-map');
    let aligatorMarker = document.querySelector('.aligator-map');
    let elefantMarker = document.querySelector('.elephante-map');
    let pinguineMarker = document.querySelector('.penguin-map');
    let gorilaMarker = document.querySelector('.gorila-map');
    let pandaMarker = document.querySelector('.panda-map');
    
    const mapPositions = [
        {   
            width: 1440,
            min: 0.8,
            max: 0.9,
            eagleLeft: '260px',
            eagleTop: '390px',
            aligatorLeft: '360px',
            aligatorTop: '470px',
            gorilaLeft: '710px',
            gorilaTop: '530px',
            elefantLeft: '750px',
            elefantTop: '660px',
            pinguineLeft: '440px',
            pinguineTop: '710px',
            pandaLeft: '940px',
            pandaTop: '410px',
        }, 
        {
            width: 1440,
            min: 0.9,
            max: 1,
            eagleLeft: '210px',
            eagleTop: '390px',
            aligatorLeft: '320px',
            aligatorTop: '470px',
            gorilaLeft: '710px',
            gorilaTop: '540px',
            elefantLeft: '750px',
            elefantTop: '700px',
            pinguineLeft: '410px',
            pinguineTop: '760px',
            pandaLeft: '960px',
            pandaTop: '410px',
        },
         {
            width: 1440,
            min: 1,
            max: 1.1,
            eagleLeft: '160px',
            eagleTop: '390px',
            aligatorLeft: '300px',
            aligatorTop: '470px',
            gorilaLeft: '710px',
            gorilaTop: '540px',
            elefantLeft: '750px',
            elefantTop: '710px',
            pinguineLeft: '370px',
            pinguineTop: '800px',
            pandaLeft: '980px',
            pandaTop: '410px',
        },
         {
            width: 1440,
            min: 1.1,
            max: 1.2,
            eagleLeft: '110px',
            eagleTop: '390px',
            aligatorLeft: '250px',
            aligatorTop: '470px',
            gorilaLeft: '710px',
            gorilaTop: '550px',
            elefantLeft: '750px',
            elefantTop: '750px',
            pinguineLeft: '340px',
            pinguineTop: '850px',
            pandaLeft: '1000px',
            pandaTop: '410px',
        },
         {
            width: 1440,
            min: 1.2,
            max: 1.3,
            eagleLeft: '50px',
            eagleTop: '390px',
            aligatorLeft: '200px',
            aligatorTop: '470px',
            gorilaLeft: '710px',
            gorilaTop: '570px',
            elefantLeft: '750px',
            elefantTop: '780px',
            pinguineLeft: '320px',
            pinguineTop: '850px',
            pandaLeft: '1020px',
            pandaTop: '410px',
        },
        {
            width: 1440,
            min: 1.3,
            max: 1.4,
            eagleLeft: '20px',
            eagleTop: '390px',
            aligatorLeft: '170px',
            aligatorTop: '490px',
            gorilaLeft: '710px',
            gorilaTop: '580px',
            elefantLeft: '750px',
            elefantTop: '820px',
            pinguineLeft: '280px',
            pinguineTop: '920px',
            pandaLeft: '1070px',
            pandaTop: '410px',
        },
        {
            width: 1440,
            min: 1.4,
            max: 1.5,
            eagleLeft: '20px',
            eagleTop: '390px',
            aligatorLeft: '130px',
            aligatorTop: '495px',
            gorilaLeft: '710px',
            gorilaTop: '600px',
            elefantLeft: '760px',
            elefantTop: '860px',
            pinguineLeft: '250px',
            pinguineTop: '960px',
            pandaLeft: '1100px',
            pandaTop: '410px',
        },
         {
            width: 1440,
            min: 1.5,
            max: 1.6,
            eagleLeft: '20px',
            eagleTop: '390px',
            aligatorLeft: '90px',
            aligatorTop: '495px',
            gorilaLeft: '710px',
            gorilaTop: '615px',
            elefantLeft: '780px',
            elefantTop: '880px',
            pinguineLeft: '220px',
            pinguineTop: '1000px',
            pandaLeft: '1130px',
            pandaTop: '410px',
        },
        
        {   
            width: 1200,
            min: 0.8,
            max: 0.9,
            eagleLeft: '260px',
            eagleTop: '390px',
            aligatorLeft: '360px',
            aligatorTop: '470px',
            gorilaLeft: '710px',
            gorilaTop: '530px',
            elefantLeft: '750px',
            elefantTop: '660px',
            pinguineLeft: '440px',
            pinguineTop: '710px',
            pandaLeft: '940px',
            pandaTop: '410px',
        }, 
        {
            width: 1200,
            min: 0.9,
            max: 1,
            eagleLeft: '200px',
            eagleTop: '390px',
            aligatorLeft: '330px',
            aligatorTop: '470px',
            gorilaLeft: '710px',
            gorilaTop: '540px',
            elefantLeft: '750px',
            elefantTop: '700px',
            pinguineLeft: '410px',
            pinguineTop: '760px',
            pandaLeft: '960px',
            pandaTop: '410px',
        },
         {
            width: 1200,
            min: 1,
            max: 1.1,
            eagleLeft: '160px',
            eagleTop: '390px',
            aligatorLeft: '300px',
            aligatorTop: '470px',
            gorilaLeft: '710px',
            gorilaTop: '540px',
            elefantLeft: '750px',
            elefantTop: '710px',
            pinguineLeft: '370px',
            pinguineTop: '800px',
            pandaLeft: '980px',
            pandaTop: '410px',
        },
         {
            width: 1200,
            min: 1.1,
            max: 1.2,
            eagleLeft: '110px',
            eagleTop: '390px',
            aligatorLeft: '250px',
            aligatorTop: '470px',
            gorilaLeft: '710px',
            gorilaTop: '550px',
            elefantLeft: '750px',
            elefantTop: '750px',
            pinguineLeft: '340px',
            pinguineTop: '850px',
            pandaLeft: '1000px',
            pandaTop: '410px',
        },
         {
            width: 1200,
            min: 1.2,
            max: 1.3,
            eagleLeft: '50px',
            eagleTop: '390px',
            aligatorLeft: '200px',
            aligatorTop: '470px',
            gorilaLeft: '710px',
            gorilaTop: '570px',
            elefantLeft: '750px',
            elefantTop: '780px',
            pinguineLeft: '320px',
            pinguineTop: '850px',
            pandaLeft: '1020px',
            pandaTop: '410px',
        },
        {
            width: 1200,
            min: 1.3,
            max: 1.4,
            eagleLeft: '20px',
            eagleTop: '390px',
            aligatorLeft: '170px',
            aligatorTop: '490px',
            gorilaLeft: '710px',
            gorilaTop: '580px',
            elefantLeft: '750px',
            elefantTop: '820px',
            pinguineLeft: '280px',
            pinguineTop: '920px',
            pandaLeft: '1070px',
            pandaTop: '410px',
        },
        {
            width: 1200,
            min: 1.4,
            max: 1.5,
            eagleLeft: '20px',
            eagleTop: '390px',
            aligatorLeft: '130px',
            aligatorTop: '495px',
            gorilaLeft: '710px',
            gorilaTop: '600px',
            elefantLeft: '760px',
            elefantTop: '860px',
            pinguineLeft: '250px',
            pinguineTop: '960px',
            pandaLeft: '1100px',
            pandaTop: '410px',
        },
         {
            width: 1200,
            min: 1.5,
            max: 1.6,
            eagleLeft: '-10px',
            eagleTop: '390px',
            aligatorLeft: '90px',
            aligatorTop: '495px',
            gorilaLeft: '710px',
            gorilaTop: '615px',
            elefantLeft: '780px',
            elefantTop: '880px',
            pinguineLeft: '220px',
            pinguineTop: '1000px',
            pandaLeft: '1130px',
            pandaTop: '410px',
        },


        {   
            width: 1024,
            min: 0.8,
            max: 0.9,
            eagleLeft: '210px',
            eagleTop: '280px',
            aligatorLeft: '280px',
            aligatorTop: '330px',
            gorilaLeft: '540px',
            gorilaTop: '380px',
            elefantLeft: '560px',
            elefantTop: '480px',
            pinguineLeft: '330px',
            pinguineTop: '530px',
            pandaLeft: '710px',
            pandaTop: '300px',
        }, 
        {
            width: 1024,
            min: 0.9,
            max: 1,
            eagleLeft: '160px',
            eagleTop: '280px',
            aligatorLeft: '240px',
            aligatorTop: '330px',
            gorilaLeft: '540px',
            gorilaTop: '390px',
            elefantLeft: '580px',
            elefantTop: '520px',
            pinguineLeft: '300px',
            pinguineTop: '560px',
            pandaLeft: '710px',
            pandaTop: '300px',
        },
         {
            width: 1024,
            min: 1,
            max: 1.1,
            eagleLeft: '100px',
            eagleTop: '270px',
            aligatorLeft: '200px',
            aligatorTop: '330px',
            gorilaLeft: '540px',
            gorilaTop: '390px',
            elefantLeft: '580px',
            elefantTop: '540px',
            pinguineLeft: '290px',
            pinguineTop: '595px',
            pandaLeft: '750px',
            pandaTop: '300px',
        },
         {
            width: 1024,
            min: 1.1,
            max: 1.2,
            eagleLeft: '90px',
            eagleTop: '270px',
            aligatorLeft: '170px',
            aligatorTop: '345px',
            gorilaLeft: '540px',
            gorilaTop: '390px',
            elefantLeft: '580px',
            elefantTop: '560px',
            pinguineLeft: '280px',
            pinguineTop: '595px',
            pandaLeft: '770px',
            pandaTop: '300px',
        },
         {
            width: 1024,
            min: 1.2,
            max: 1.3,
            eagleLeft: '50px',
            eagleTop: '270px',
            aligatorLeft: '160px',
            aligatorTop: '340px',
            gorilaLeft: '540px',
            gorilaTop: '400px',
            elefantLeft: '580px',
            elefantTop: '590px',
            pinguineLeft: '240px',
            pinguineTop: '640px',
            pandaLeft: '790px',
            pandaTop: '300px',
        },
        {
            width: 1024,
            min: 1.3,
            max: 1.4,
            eagleLeft: '20px',
            eagleTop: '270px',
            aligatorLeft: '120px',
            aligatorTop: '350px',
            gorilaLeft: '540px',
            gorilaTop: '420px',
            elefantLeft: '580px',
            elefantTop: '605px',
            pinguineLeft: '225px',
            pinguineTop: '675px',
            pandaLeft: '815px',
            pandaTop: '300px',
        },
        {
            width: 1024,
            min: 1.4,
            max: 1.5,
            eagleLeft: '0px',
            eagleTop: '270px',
            aligatorLeft: '90px',
            aligatorTop: '355px',
            gorilaLeft: '540px',
            gorilaTop: '440px',
            elefantLeft: '580px',
            elefantTop: '630px',
            pinguineLeft: '200px',
            pinguineTop: '700px',
            pandaLeft: '830px',
            pandaTop: '300px',
        },
         {
            width: 1024,
            min: 1.5,
            max: 1.6,
            eagleLeft: '0px',
            eagleTop: '270px',
            aligatorLeft: '65px',
            aligatorTop: '355px',
            gorilaLeft: '540px',
            gorilaTop: '440px',
            elefantLeft: '580px',
            elefantTop: '640px',
            pinguineLeft: '175px',
            pinguineTop: '740px',
            pandaLeft: '860px',
            pandaTop: '300px',
        },

        {   
            width: 990,
            min: 0.8,
            max: 0.9,
            eagleLeft: '210px',
            eagleTop: '280px',
            aligatorLeft: '280px',
            aligatorTop: '330px',
            gorilaLeft: '540px',
            gorilaTop: '380px',
            elefantLeft: '560px',
            elefantTop: '480px',
            pinguineLeft: '330px',
            pinguineTop: '530px',
            pandaLeft: '710px',
            pandaTop: '300px',
        }, 
        {
            width: 990,
            min: 0.9,
            max: 1,
            eagleLeft: '160px',
            eagleTop: '280px',
            aligatorLeft: '240px',
            aligatorTop: '330px',
            gorilaLeft: '540px',
            gorilaTop: '390px',
            elefantLeft: '580px',
            elefantTop: '520px',
            pinguineLeft: '300px',
            pinguineTop: '560px',
            pandaLeft: '710px',
            pandaTop: '300px',
        },
         {
            width: 990,
            min: 1,
            max: 1.1,
            eagleLeft: '100px',
            eagleTop: '270px',
            aligatorLeft: '200px',
            aligatorTop: '330px',
            gorilaLeft: '540px',
            gorilaTop: '390px',
            elefantLeft: '580px',
            elefantTop: '540px',
            pinguineLeft: '290px',
            pinguineTop: '595px',
            pandaLeft: '750px',
            pandaTop: '300px',
        },
         {
            width: 990,
            min: 1.1,
            max: 1.2,
            eagleLeft: '90px',
            eagleTop: '270px',
            aligatorLeft: '170px',
            aligatorTop: '345px',
            gorilaLeft: '540px',
            gorilaTop: '390px',
            elefantLeft: '580px',
            elefantTop: '560px',
            pinguineLeft: '280px',
            pinguineTop: '595px',
            pandaLeft: '770px',
            pandaTop: '300px',
        },
         {
            width: 990,
            min: 1.2,
            max: 1.3,
            eagleLeft: '50px',
            eagleTop: '270px',
            aligatorLeft: '160px',
            aligatorTop: '340px',
            gorilaLeft: '540px',
            gorilaTop: '400px',
            elefantLeft: '580px',
            elefantTop: '590px',
            pinguineLeft: '240px',
            pinguineTop: '640px',
            pandaLeft: '790px',
            pandaTop: '300px',
        },
        {
            width: 990,
            min: 1.3,
            max: 1.4,
            eagleLeft: '20px',
            eagleTop: '270px',
            aligatorLeft: '120px',
            aligatorTop: '350px',
            gorilaLeft: '540px',
            gorilaTop: '420px',
            elefantLeft: '580px',
            elefantTop: '605px',
            pinguineLeft: '225px',
            pinguineTop: '675px',
            pandaLeft: '815px',
            pandaTop: '300px',
        },
        {
            width: 990,
            min: 1.4,
            max: 1.5,
            eagleLeft: '-10px',
            eagleTop: '270px',
            aligatorLeft: '90px',
            aligatorTop: '355px',
            gorilaLeft: '540px',
            gorilaTop: '440px',
            elefantLeft: '580px',
            elefantTop: '630px',
            pinguineLeft: '200px',
            pinguineTop: '700px',
            pandaLeft: '830px',
            pandaTop: '300px',
        },
         {
            width: 990,
            min: 1.5,
            max: 1.6,
            eagleLeft: '-10px',
            eagleTop: '270px',
            aligatorLeft: '65px',
            aligatorTop: '355px',
            gorilaLeft: '540px',
            gorilaTop: '440px',
            elefantLeft: '580px',
            elefantTop: '640px',
            pinguineLeft: '175px',
            pinguineTop: '740px',
            pandaLeft: '860px',
            pandaTop: '300px',
        },

        {   
            width: 768,
            min: 0.8,
            max: 0.9,
            eagleLeft: '210px',
            eagleTop: '280px',
            aligatorLeft: '280px',
            aligatorTop: '330px',
            gorilaLeft: '540px',
            gorilaTop: '380px',
            elefantLeft: '560px',
            elefantTop: '480px',
            pinguineLeft: '330px',
            pinguineTop: '530px',
            pandaLeft: '710px',
            pandaTop: '300px',
        }, 
        {
            width: 768,
            min: 0.9,
            max: 1,
            eagleLeft: '160px',
            eagleTop: '280px',
            aligatorLeft: '240px',
            aligatorTop: '330px',
            gorilaLeft: '540px',
            gorilaTop: '390px',
            elefantLeft: '580px',
            elefantTop: '520px',
            pinguineLeft: '300px',
            pinguineTop: '560px',
            pandaLeft: '710px',
            pandaTop: '300px',
        },
         {
            width: 768,
            min: 1,
            max: 1.1,
            eagleLeft: '100px',
            eagleTop: '270px',
            aligatorLeft: '200px',
            aligatorTop: '330px',
            gorilaLeft: '540px',
            gorilaTop: '390px',
            elefantLeft: '580px',
            elefantTop: '540px',
            pinguineLeft: '290px',
            pinguineTop: '595px',
            pandaLeft: '750px',
            pandaTop: '300px',
        },
         {
            width: 768,
            min: 1.1,
            max: 1.2,
            eagleLeft: '90px',
            eagleTop: '270px',
            aligatorLeft: '170px',
            aligatorTop: '345px',
            gorilaLeft: '540px',
            gorilaTop: '390px',
            elefantLeft: '580px',
            elefantTop: '560px',
            pinguineLeft: '280px',
            pinguineTop: '595px',
            pandaLeft: '770px',
            pandaTop: '300px',
        },
         {
            width: 768,
            min: 1.2,
            max: 1.3,
            eagleLeft: '50px',
            eagleTop: '270px',
            aligatorLeft: '160px',
            aligatorTop: '340px',
            gorilaLeft: '540px',
            gorilaTop: '400px',
            elefantLeft: '580px',
            elefantTop: '590px',
            pinguineLeft: '240px',
            pinguineTop: '640px',
            pandaLeft: '790px',
            pandaTop: '300px',
        },
        {
            width: 768,
            min: 1.3,
            max: 1.4,
            eagleLeft: '20px',
            eagleTop: '270px',
            aligatorLeft: '120px',
            aligatorTop: '350px',
            gorilaLeft: '540px',
            gorilaTop: '420px',
            elefantLeft: '580px',
            elefantTop: '605px',
            pinguineLeft: '225px',
            pinguineTop: '675px',
            pandaLeft: '815px',
            pandaTop: '300px',
        },
        {
            width: 768,
            min: 1.4,
            max: 1.5,
            eagleLeft: '-10px',
            eagleTop: '270px',
            aligatorLeft: '90px',
            aligatorTop: '355px',
            gorilaLeft: '540px',
            gorilaTop: '440px',
            elefantLeft: '580px',
            elefantTop: '630px',
            pinguineLeft: '200px',
            pinguineTop: '700px',
            pandaLeft: '830px',
            pandaTop: '300px',
        },
         {
            width: 768,
            min: 1.5,
            max: 1.6,
            eagleLeft: '-10px',
            eagleTop: '270px',
            aligatorLeft: '65px',
            aligatorTop: '355px',
            gorilaLeft: '540px',
            gorilaTop: '440px',
            elefantLeft: '580px',
            elefantTop: '640px',
            pinguineLeft: '175px',
            pinguineTop: '740px',
            pandaLeft: '860px',
            pandaTop: '300px',
        },

        {   
            width: 640,
            min: 0.8,
            max: 0.9,
            eagleLeft: '90px',
            eagleTop: '200px',
            aligatorLeft: '140px',
            aligatorTop: '220px',
            gorilaLeft: '295px',
            gorilaTop: '255px',
            elefantLeft: '300px',
            elefantTop: '330px',
            pinguineLeft: '160px',
            pinguineTop: '355px',
            pandaLeft: '400px',
            pandaTop: '210px',
        }, 
        {
            width: 640,
            min: 0.9,
            max: 1,
            eagleLeft: '70px',
            eagleTop: '200px',
            aligatorLeft: '120px',
            aligatorTop: '220px',
            gorilaLeft: '295px',
            gorilaTop: '255px',
            elefantLeft: '300px',
            elefantTop: '350px',
            pinguineLeft: '155px',
            pinguineTop: '363px',
            pandaLeft: '420px',
            pandaTop: '210px',
        },
         {
            width: 640,
            min: 1,
            max: 1.1,
            eagleLeft: '60px',
            eagleTop: '200px',
            aligatorLeft: '110px',
            aligatorTop: '220px',
            gorilaLeft: '295px',
            gorilaTop: '255px',
            elefantLeft: '300px',
            elefantTop: '350px',
            pinguineLeft: '150px',
            pinguineTop: '370px',
            pandaLeft: '420px',
            pandaTop: '210px',
        },
         {
            width: 640,
            min: 1.1,
            max: 1.2,
            eagleLeft: '35px',
            eagleTop: '200px',
            aligatorLeft: '90px',
            aligatorTop: '235px',
            gorilaLeft: '295px',
            gorilaTop: '255px',
            elefantLeft: '300px',
            elefantTop: '360px',
            pinguineLeft: '145px',
            pinguineTop: '390px',
            pandaLeft: '430px',
            pandaTop: '210px',
        },
         {
            width: 640,
            min: 1.2,
            max: 1.3,
            eagleLeft: '10px',
            eagleTop: '200px',
            aligatorLeft: '70px',
            aligatorTop: '235px',
            gorilaLeft: '295px',
            gorilaTop: '275px',
            elefantLeft: '305px',
            elefantTop: '375px',
            pinguineLeft: '125px',
            pinguineTop: '410px',
            pandaLeft: '435px',
            pandaTop: '210px',
        },
        {
            width: 640,
            min: 1.3,
            max: 1.4,
            eagleLeft: '0px',
            eagleTop: '200px',
            aligatorLeft: '50px',
            aligatorTop: '235px',
            gorilaLeft: '295px',
            gorilaTop: '280px',
            elefantLeft: '310px',
            elefantTop: '385px',
            pinguineLeft: '110px',
            pinguineTop: '440px',
            pandaLeft: '450px',
            pandaTop: '210px',
        },
        {
            width: 640,
            min: 1.4,
            max: 1.5,
            eagleLeft: '-10px',
            eagleTop: '200px',
            aligatorLeft: '40px',
            aligatorTop: '245px',
            gorilaLeft: '295px',
            gorilaTop: '295px',
            elefantLeft: '320px',
            elefantTop: '405px',
            pinguineLeft: '95px',
            pinguineTop: '450px',
            pandaLeft: '465px',
            pandaTop: '210px',
        },
         {
            width: 640,
            min: 1.5,
            max: 1.6,
            eagleLeft: '-10px',
            eagleTop: '200px',
            aligatorLeft: '30px',
            aligatorTop: '245px',
            gorilaLeft: '295px',
            gorilaTop: '300px',
            elefantLeft: '320px',
            elefantTop: '420px',
            pinguineLeft: '80px',
            pinguineTop: '470px',
            pandaLeft: '480px',
            pandaTop: '210px',
        },

    ];

    for(let item of mapPositions) {
        if(containerWidth === item.width && scale >= item.min && scale < item.max) {
            eagleMarker.style.left = item.eagleLeft;
            eagleMarker.style.top = item.eagleTop;
            aligatorMarker.style.left = item.aligatorLeft;
            aligatorMarker.style.top = item.aligatorTop;
            pinguineMarker.style.left = item.pinguineLeft;
            pinguineMarker.style.top = item.pinguineTop;
            gorilaMarker.style.left = item.gorilaLeft;
            gorilaMarker.style.top = item.gorilaTop;
            elefantMarker.style.left = item.elefantLeft;
            elefantMarker.style.top = item.elefantTop;
            pandaMarker.style.left = item.pandaLeft;
            pandaMarker.style.top = item.pandaTop;
        }
    }



}

transformMap(zoomInBtn, scale);
transformMap(zoomOutBtn, scale);
